sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t burakunuvar/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true burakunuvar/react-test npm test

after_success:
  - docker build -t burakunuvar/multi-client-02-11 ./client
  - docker build -t burakunuvar/multi-nginx-02-11 ./nginx
  - docker build -t burakunuvar/multi-server-02-11 ./server
  - docker build -t burakunuvar/multi-worker-02-11 ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push burakunuvar/multi-client-02-11
  - docker push burakunuvar/multi-nginx-02-11
  - docker push burakunuvar/multi-server-02-11
  - docker push burakunuvar/multi-worker-02-11

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-388521517294"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
